# Generated by Django 6.0.4 on 2026-07-29 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('customers', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_reminder_24h', 'Booking Reminder — 24hr'), ('booking_reminder_2h', 'Booking Reminder — 2hr'), ('payment_status', 'Payment Status Change'), ('new_booking_alert', 'New Booking Alert'), ('generic', 'Generic')], default='generic', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('fcm_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.user')),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_e78525_idx')],
            },
        ),
    ]
