# Generated by Django 6.0.4 on 2026-05-07 06:46

import django.db.models.deletion
import django.utils.timezone
import sunndari_apps.artists.models.portfolio
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('service_radius_km', models.PositiveIntegerField(default=10)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.approvalstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to='authentication.user')),
            ],
            options={
                'db_table': 'artist_profiles',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=sunndari_apps.artists.models.portfolio.portfolio_upload_path)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.approvalstatus')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='artists.artistprofile')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='core.servicesubcategory')),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_packages', to='artists.artistprofile')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_packages', to='core.servicesubcategory')),
            ],
            options={
                'db_table': 'pricing_packages',
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('inclusion_id', models.AutoField(primary_key=True, serialize=False)),
                ('inclusion_text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='artists.pricingpackage')),
            ],
            options={
                'db_table': 'package_inclusions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArtistLocationPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artist_preferences', to='core.locationtype')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_preferences', to='artists.artistprofile')),
            ],
            options={
                'db_table': 'artist_location_preferences',
                'unique_together': {('artist', 'location_type')},
            },
        ),
        migrations.CreateModel(
            name='ArtistAvailabilitySchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('location_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.locationtype')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedules', to='artists.artistprofile')),
            ],
            options={
                'db_table': 'artist_availability_schedules',
                'unique_together': {('artist', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='ArtistAvailabilityBlock',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='artists.artistprofile')),
            ],
            options={
                'db_table': 'artist_availability_blocks',
                'unique_together': {('artist', 'block_date')},
            },
        ),
        migrations.CreateModel(
            name='ArtistServiceOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='artists.artistprofile')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artist_offerings', to='core.servicesubcategory')),
            ],
            options={
                'db_table': 'artist_service_offerings',
                'unique_together': {('artist', 'sub_category')},
            },
        ),
    ]
