# Generated by Django 6.0.4 on 2026-09-25 07:26

import django.db.models.deletion
import django.utils.timezone
import sunndari_apps.artists.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='base_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profiles', to='users.customeraddress'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ArtistDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('certification', 'Professional Certification')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to=sunndari_apps.artists.models.document.artist_document_upload_path)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='artists.artistprofile')),
                ('verification_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.approvalstatus')),
            ],
            options={
                'db_table': 'artist_documents',
            },
        ),
        migrations.CreateModel(
            name='ArtistPayoutAccount',
            fields=[
                ('payout_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to='artists.artistprofile')),
                ('verification_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.approvalstatus')),
            ],
            options={
                'db_table': 'artist_payout_accounts',
            },
        ),
    ]
