# Generated by Django 6.0.4 on 2026-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artistprofile_base_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
