# Generated by Django 6.0.4 on 2026-10-03 09:34

import sunndari_apps.artists.models.document
import sunndari_apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistprofile_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdocument',
            name='file',
            field=models.FileField(storage=sunndari_apps.common.storage.PrivateMediaStorage(), upload_to=sunndari_apps.artists.models.document.artist_document_upload_path),
        ),
    ]
