# Generated by Django 6.0.4 on 2026-10-03 09:50

import sunndari_apps.artists.models.document
import sunndari_apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_kyc_documents_private_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdocument',
            name='back_file',
            field=models.FileField(blank=True, null=True, storage=sunndari_apps.common.storage.PrivateMediaStorage(), upload_to=sunndari_apps.artists.models.document.artist_document_back_upload_path),
        ),
        migrations.AddField(
            model_name='artistdocument',
            name='document_number_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistdocument',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('driving_licence', 'Driving Licence')], max_length=20, null=True),
        ),
    ]
