# Generated by Django 6.0.4 on 2026-10-03 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_kyc_id_types_and_back_image'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('freelance', 'Freelance'), ('studio', 'Studio')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_work_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ArtistSpeciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='artists.artistprofile')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_specialities', to='core.servicesubcategory')),
            ],
            options={
                'db_table': 'artist_specialities',
                'unique_together': {('artist', 'sub_category')},
            },
        ),
    ]
