# Generated by Django 6.0.4 on 2026-10-03 09:55

import sunndari_apps.artists.models.artist_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_registration_fields_specialities_work_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to=sunndari_apps.artists.models.artist_profile.artist_photo_upload_path),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=sunndari_apps.artists.models.artist_profile.artist_photo_upload_path),
        ),
    ]
