# Generated by Django 6.0.4 on 2026-10-03 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_profile_cover_photos'),
        ('authentication', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistReviewFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_review_feedback_given', to='authentication.user')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_feedback', to='artists.artistprofile')),
            ],
            options={
                'db_table': 'artist_review_feedback',
                'indexes': [models.Index(fields=['artist', '-created_at'], name='artist_revi_artist__0cdd9f_idx')],
            },
        ),
    ]
