# Generated by Django 6.0.4 on 2026-10-03 09:58

import sunndari_apps.artists.models.pricing_package
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_review_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpackage',
            name='brands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='makeup_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=sunndari_apps.artists.models.pricing_package.package_photo_upload_path),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='product_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
