# Generated by Django 6.0.4 on 2026-10-03 10:00

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_package_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='return_buffer_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='travel_time_before_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArtistServiceArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('travel_charge_type', models.CharField(choices=[('free', 'Free'), ('per_visit', 'Per visit'), ('per_km', 'Per kilometre')], default='free', max_length=10)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='artists.artistprofile')),
            ],
            options={
                'db_table': 'artist_service_areas',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('city'), models.F('artist'), name='unique_service_area_city_per_artist')],
            },
        ),
        migrations.CreateModel(
            name='PackageAddOn',
            fields=[
                ('addon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='artists.artistprofile')),
                ('packages', models.ManyToManyField(blank=True, related_name='addons', to='artists.pricingpackage')),
            ],
            options={
                'db_table': 'package_addons',
                'indexes': [models.Index(fields=['artist'], name='package_add_artist__f5a44c_idx')],
            },
        ),
    ]
