# Generated by Django 6.0.4 on 2026-10-03 10:16

from django.db import migrations, models


def encrypt_existing(apps, schema_editor):
    from sunndari_apps.common.crypto import encrypt_text
    Account = apps.get_model('artists', 'ArtistPayoutAccount')
    for account in Account.objects.all():
        # Fernet tokens always start with 'gAAAA'; skip anything already encrypted (re-runnable).
        if account.bank_account_number and not account.bank_account_number.startswith('gAAAA'):
            account.bank_account_number = encrypt_text(account.bank_account_number)
            account.save(update_fields=['bank_account_number'])


def decrypt_existing(apps, schema_editor):
    from sunndari_apps.common.crypto import decrypt_text
    Account = apps.get_model('artists', 'ArtistPayoutAccount')
    for account in Account.objects.all():
        plain = decrypt_text(account.bank_account_number)
        if plain:
            account.bank_account_number = plain[:30]
            account.save(update_fields=['bank_account_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_add_ons_service_areas_booking_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpayoutaccount',
            name='bank_account_number',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
