# Generated by Django 6.0.4 on 2026-10-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_payout_account_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='agreement_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='is_accepting_bookings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='profile_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
