# Generated by Django 6.0.4 on 2026-10-03 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_profile_switch_slug_views_sort_order'),
        ('authentication', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistClientNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='artists.artistprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_notes_about', to='authentication.user')),
            ],
            options={
                'db_table': 'artist_client_notes',
                'unique_together': {('artist', 'customer')},
            },
        ),
    ]
