# Generated by Django 6.0.4 on 2026-10-03 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_reviews_replies_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.CharField(blank=True, max_length=300, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_requests', to='artists.artistprofile')),
            ],
            options={
                'db_table': 'brand_requests',
                'indexes': [models.Index(fields=['status', 'created_at'], name='brand_reque_status_f4a4f0_idx')],
            },
        ),
    ]
