# Generated by Django 6.0.4 on 2026-09-17 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_user_fcm_token'),
        ('customers', '0005_relocate_payment_to_payments_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('coin_value_rupees', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('coin_expiry_days', models.PositiveIntegerField(default=365)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coin_configs',
            },
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to='authentication.user')),
                ('balance_coins', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_wallets',
            },
        ),
        migrations.CreateModel(
            name='RedemptionTier',
            fields=[
                ('tier_id', models.AutoField(primary_key=True, serialize=False)),
                ('rupee_value', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('coin_cost', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'redemption_tiers',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CASHBACK', 'Cashback'), ('REDEMPTION', 'Redemption'), ('REVERSAL', 'Reversal'), ('EXPIRY', 'Expiry'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('coins', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('remaining_coins', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rupee_equivalent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_transactions', to='customers.booking')),
                ('reference_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='wallet.cointransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.customerwallet')),
            ],
            options={
                'db_table': 'coin_transactions',
                'indexes': [models.Index(fields=['wallet'], name='coin_transa_wallet__6b7380_idx'), models.Index(fields=['booking'], name='coin_transa_booking_ea079b_idx')],
            },
        ),
    ]
