# Generated by Django 6.0.4 on 2026-09-17 09:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinconfig',
            name='coin_value_rupees',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=6),
        ),
    ]
