# Generated by Django 6.0.4 on 2026-09-17 10:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_coinconfig_coin_value_rupees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinconfig',
            name='cashback_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='coinconfig',
            name='coin_value_rupees',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
