# Generated by Django 6.0.4 on 2026-09-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_relocate_payment_to_payments_app'),
        ('wallet', '0003_alter_coinconfig_cashback_percentage_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cointransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'CASHBACK')), fields=('booking',), name='unique_cashback_per_booking'),
        ),
    ]
