# Generated by Django 6.0.4 on 2026-09-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wallet', '0004_cointransaction_unique_cashback_per_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_transactions', to='payments.payment'),
        ),
    ]
