# Generated by Django 6.0.4 on 2026-09-18 05:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_cointransaction_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinconfig',
            name='coin_value_rupees',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
