# Generated by Django 6.0.4 on 2026-08-18 07:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('running', 'Running'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to='authentication.user')),
            ],
            options={
                'db_table': 'support_conversations',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='help_center.supportconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='authentication.user')),
            ],
            options={
                'db_table': 'support_messages',
            },
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['customer', 'status'], name='support_con_custome_da494a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='support_mes_convers_c7d2f0_idx'),
        ),
    ]
