# Generated by Django 6.0.4 on 2026-10-03 10:23

import django.db.models.deletion
import django.utils.timezone
import sunndari_apps.common.storage
import sunndari_apps.help_center.models.ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_fcm_token'),
        ('customers', '0008_reviews_replies_clients'),
        ('help_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('service_quality', 'Service quality'), ('account', 'Account'), ('technical', 'Technical problem'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=12)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='customers.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='authentication.user')),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=sunndari_apps.common.storage.PrivateMediaStorage(), upload_to=sunndari_apps.help_center.models.ticket.ticket_attachment_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='help_center.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='support_tic_user_id_057736_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='support_tic_status_627203_idx'),
        ),
    ]
