class Constants:
    # Auth
    validation_error = 'Validation Error'
    auth_error = 'Authentication Error'
    server_error = 'Server Error'
    access_token_expired = 'Expired access token'
    refresh_token_invalid = 'Invalid refresh token'
    invalid_header = 'Invalid authorization header'
    auth_success = 'Authentication successful'
    invalid_access_token = 'Invalid access token'
    forbidden_access = 'Forbidden access'

    # OTP
    otp_sent = 'OTP sent successfully'
    otp_invalid = 'Invalid or expired OTP'
    password_reset_otp_sent = 'If the account exists, a verification code has been sent'
    password_reset_success = 'Password reset successfully'
    otp_max_attempts = 'Maximum OTP attempts exceeded'
    account_locked = 'Account locked. Please try again after 30 minutes'

    # User
    mobile_number_not_unique = 'The mobile number already exists, please provide another mobile number'
    email_not_unique = 'The email already exists, please provide another email'
    user_not_found = 'User not found'
    user_already_exists = 'User already exists. Please login instead'

    # General
    page_num_exceeded = 'The given page number is greater than maximum available limit'
    delete_not_allowed = 'Deleting records is not allowed'
    item_not_found = 'Item not found'
    forbidden_resource = 'Not allowed to access this resource'
    data_get = 'Data fetched successfully'
    data_no_match = 'No matching record found'

    # Artist
    artist_not_found = 'Artist not found'
    artist_not_approved = 'Artist profile is not approved'
    artist_requires_package = 'Artist must have at least one active package'
    artist_already_approved = 'Artist profile is already approved'
    artist_suspended = 'Artist account is suspended; contact support'
    onboarding_not_submitted = 'Artist has not submitted onboarding for review'

    # Booking
    slot_unavailable = 'The selected time slot is not available'
    booking_not_found = 'Booking not found'
    booking_already_reviewed = 'This booking has already been reviewed'
    booking_not_completed = 'Review can only be submitted after the service is completed'
    slot_locked = 'Slot locked for 15 minutes pending payment'
    double_booking = 'This slot is already booked'
    on_my_way_not_allowed = 'Booking must be confirmed and not already marked as on the way'
    on_my_way_too_early = 'On My Way can only be marked within 2 hours of the booking start time'
    arrived_not_allowed = 'Artist must be marked as on the way, and not already arrived, to confirm arrival'
    start_pin_not_available = 'Start Service PIN is not available yet'
    start_pin_verify_not_allowed = 'Artist must have arrived to start the service'
    start_pin_invalid = 'Invalid or expired Start Service PIN'
    completion_pin_not_available = 'Completion PIN is not available yet'
    completion_pin_verify_not_allowed = 'Service must be in progress to mark it as completed'
    completion_pin_invalid = 'Invalid or expired Completion PIN'
    past_date_booking = 'Cannot book a date in the past'
    booking_too_soon = 'Bookings must be made at least 2 hours in advance'
    booking_expired = 'This booking has expired and cannot be updated'
    payment_required_to_confirm = 'This booking cannot be confirmed until payment has been completed'
    package_unavailable = 'This package is currently unavailable'

    # Payment
    payment_not_found = 'Payment record not found'
    payment_already_completed = 'Booking is already fully paid'
    invalid_payment_amount = 'Payment amount exceeds the remaining amount due'
    payment_signature_invalid = 'Payment signature verification failed'
    payment_not_verifiable = 'This payment cannot be verified in its current state'
    payment_verification_mismatch = 'Payment could not be verified with the payment gateway'
    duplicate_booking_in_group = 'The same booking_id cannot appear more than once in a group payment'

    # Wallet
    redemption_tier_not_found = 'Selected redemption tier is not available'
    redemption_exceeds_amount = 'Selected redemption tier exceeds the payable amount'
    wallet_busy_please_retry = 'Your wallet is currently busy processing another request. Please try again in a moment.'

    # Portfolio
    portfolio_limit_exceeded = 'Maximum 20 active portfolio items allowed'
    file_required = 'A file is required to create a portfolio item'
    kyc_id_type_required = 'id_type is required for an ID proof'
    kyc_id_type_not_allowed = 'id_type is only valid for an ID proof'
    kyc_number_required = 'document_number is required for an ID proof'
    kyc_back_required = 'A back image is required for this ID type'
    kyc_not_verified = 'The artist has no verified ID proof; verify the identity document first'
    document_already_decided = 'This document has already been decided'
    work_sample_limit_exceeded = 'Maximum 5 work samples allowed'
    speciality_not_offered = 'A speciality must be one of your offered services'
    photo_required = 'Upload at least one of profile_photo or cover_photo'
    per_km_unavailable = 'Per-kilometre travel charges are not available yet; use free or per_visit'
    service_area_exists = 'You already have a service area for this city'
    service_area_outside = 'The artist does not travel to the selected address city'
    service_area_address_required = 'An address is required for a home visit with this artist'
    addon_not_available = 'One or more selected add-ons are not available for this package'
    reschedule_not_allowed = 'Only a confirmed booking that has not started can be rescheduled'
    reschedule_pending_exists = 'This booking already has a pending reschedule request'
    reschedule_same_slot = 'The proposed time is the same as the current booking time'
    reschedule_too_late = 'This booking is too close to its start time to be rescheduled'
    reschedule_not_found = 'Reschedule request not found'
    reschedule_not_pending = 'This reschedule request is no longer pending'
    artist_not_accepting = 'This artist is not accepting new bookings right now'
    brand_exists = 'A brand with this name already exists'
    brand_request_exists = 'You already have a pending request for this brand'
    brand_request_limit = 'You have too many pending brand requests'
    brand_request_decided = 'This brand request has already been decided'
    ticket_too_many_attachments = 'A ticket can have at most 5 attachments'
    ticket_limit = 'You have too many open tickets; wait for some to be resolved'
    ticket_already_closed = 'This ticket is already closed'
    contact_change_requires_otp = 'To change your email or phone number, request a verification code (users/contact/change/request)'
    contact_change_one_only = 'Provide exactly one of email or phone_number'
    contact_change_same = 'This is already your current contact'
    contact_change_wait = 'A code was just sent; please wait a minute before requesting another'
    contact_change_invalid = 'Invalid or expired verification code'
    contact_change_locked = 'Too many wrong codes; request a new code'
    self_booking_not_allowed = 'You cannot book your own services'
    booking_not_cancellable = 'This booking can no longer be cancelled by the customer once the artist has arrived or the service has started'
    account_inactive = 'This account is deactivated'
    request_body_not_object = 'The request body must be a JSON object'
    password_too_common = 'This password is too common or too simple'
    payment_in_progress = 'A payment for this booking is already in progress; complete or wait for it before starting another'
    payment_overpaid = 'This payment would exceed the booking total and was not applied; it will be refunded'
    upload_empty = 'The uploaded file is empty'
    upload_too_large = 'The uploaded file is too large'
    upload_invalid_image = 'Only genuine JPEG, PNG or WEBP images are allowed'
    upload_invalid_document = 'Only JPEG, PNG, WEBP images or PDF documents are allowed'
    upload_invalid_video = 'Only MP4, MOV or WEBM videos are allowed'

    # Address
    address_limit_exceeded = 'Maximum 5 saved addresses allowed'

    # Chat
    conversation_not_found = 'Conversation not found'
    conversation_closed = 'This conversation is closed and no longer accepts new messages'
    chat_not_eligible = 'Chat is only available for confirmed or in-progress bookings'
    message_empty = 'Message content cannot be empty'
