# Generated by Django 6.0.4 on 2026-07-28 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('artist', 'Artist')], max_length=10, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.customeraddress')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='artists.artistprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_customer', to='authentication.user')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.locationtype')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='artists.pricingpackage')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.bookingstatus')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.servicesubcategory')),
            ],
            options={
                'db_table': 'bookings',
                'indexes': [models.Index(fields=['customer'], name='bookings_custome_59c648_idx'), models.Index(fields=['artist'], name='bookings_artist__af34d1_idx'), models.Index(fields=['booking_date'], name='bookings_booking_2846e7_idx')],
            },
        ),
    ]
