# Generated by Django 6.0.4 on 2026-07-29 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('full', 'Full'), ('advance', 'Advance'), ('balance', 'Balance')], default='full', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist_payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway', models.CharField(blank=True, max_length=20, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='artists.artistprofile')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_customer', to='authentication.user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.paymentstatus')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['booking'], name='payments_booking_4c4815_idx'), models.Index(fields=['customer'], name='payments_custome_8fefc3_idx')],
            },
        ),
    ]
