# Generated by Django 6.0.4 on 2026-10-03 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_fcm_token'),
        ('customers', '0006_add_ons_service_areas_booking_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReschedule',
            fields=[
                ('reschedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_date', models.DateField()),
                ('previous_start_time', models.TimeField()),
                ('previous_end_time', models.TimeField()),
                ('proposed_date', models.DateField()),
                ('proposed_start_time', models.TimeField()),
                ('proposed_end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='customers.booking')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='authentication.user')),
            ],
            options={
                'db_table': 'booking_reschedules',
                'indexes': [models.Index(fields=['booking', 'status'], name='booking_res_booking_bf44f0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('booking',), name='one_pending_reschedule_per_booking')],
            },
        ),
    ]
