# Generated by Django 6.0.4 on 2026-10-03 10:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_reviews_replies_clients'),
        ('authentication', '0002_user_fcm_token'),
        ('customers', '0007_booking_reschedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('customer_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews_written', to='artists.artistprofile')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review', to='customers.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews_received', to='authentication.user')),
            ],
            options={
                'db_table': 'customer_reviews',
                'indexes': [models.Index(fields=['artist'], name='customer_re_artist__662b21_idx'), models.Index(fields=['customer'], name='customer_re_custome_99022b_idx')],
            },
        ),
    ]
